language: node_js

branches:
    only:
        - master
env:
    global:
        secure: m3Kh6D03lkhT6DjxAjlUsns+ppSK5JeNoJznX45BgPsk0k4Q8ng1xt5RFaeeBeGlq37imOLjtz6wbV4eibtiqNX82fycC/A1mUQ8ddQ9/S+/wRwIZRq/zNjLcV4AGeWnY2DQgjA0eJU51ovDnBWAVyj2crAtmbo3UrmkJ4R72mNyMIRCqRi0MY6CQ/nXjIA9Efj6keh5oqkGVV2Qt4z+lSP3v+UZaCvPpTEA9lz/LqETI0UraI3jIvwXB5D4A9BJK49/6WVfA0QxGFBeS+wuHoapt4Avr13bZwEZ8VMbblrm0hJdvfBTND+CnaXwqmGX1K4jb94Q8E9OGGIUzqxbRyVfMerybX6SJiChqTxQqM5xG4yjL798zvoX2K+vc+2ra0lD+/KjPnvQdR+fxthEW5YNOgOIbSEknNW6cTiQezEL2jfZbNkNahfnXHbIcC2creio0kEVSE/7W9wWbiWKEnNfJTAgYM+2JwORRohWw4dkkAS3ND56/6pTm1y9GTJWwzl521sI96vSBC4xmK2CB/Tmxc14l4VcR5itFWJvSdU4D3edACVHzKlfLLXtgMneo8kGm6mgMKHcRzt+tVarSuAMddy6uK+qBfw3J8OH6ypoWHuIwEpinXXcCd0K3K9hyF55FqWFOMQKcNf+l4jskJkfgJ5Ikn4Qh7nclhOeeOo=

before_script:
    - node scripts/buildAssets.js

script:
    - npm run test
    - npm run build

notifications:
    email:
        on_failure: always

after_success:
    - "./scripts/deploy.sh"
